/**
 * PlatformIO Compiler Module
 *
 * Handles creating temporary project directories and invoking pio run.
 */

import { spawn } from 'child_process'
import fs from 'fs/promises'
import path from 'path'
import os from 'os'

export interface CompileInput {
  files: Array<{ path: string; content: string }>
  board: string
  framework: string
}

export interface CompileResult {
  success: boolean
  firmware?: Buffer
  buildOutput: string
  error?: string
}

function resolveSafeProjectPath(projectDir: string, inputPath: string): string {
  // Reject empty, absolute, or null-byte paths up front.
  if (!inputPath || inputPath.includes('\0') || path.isAbsolute(inputPath)) {
    throw new Error(`Invalid file path: ${inputPath}`)
  }

  const normalized = path.normalize(inputPath)
  const resolved = path.resolve(projectDir, normalized)
  const projectRoot = path.resolve(projectDir) + path.sep

  if (!resolved.startsWith(projectRoot)) {
    throw new Error(`Path traversal is not allowed: ${inputPath}`)
  }

  return resolved
}

/**
 * Generate platformio.ini if not provided
 */
function generatePlatformioIni(board: string, framework: string): string {
  // Map common board names to PlatformIO board IDs
  const boardMap: Record<string, string> = {
    'esp32-c6': 'esp32-c6-devkitc-1',
    'esp32c6': 'esp32-c6-devkitc-1',
    'esp32-c6-devkitc-1': 'esp32-c6-devkitc-1',
    'seeed_xiao_esp32c6': 'seeed_xiao_esp32c6',
    'esp32': 'esp32dev',
    'esp32dev': 'esp32dev',
    'esp32-s3': 'esp32-s3-devkitc-1',
    'esp32-s3-devkitc-1': 'esp32-s3-devkitc-1',
  }

  const resolvedBoard = boardMap[board.toLowerCase()] || board

  // Check if this is a board that needs USB CDC configuration (C6, S3)
  const usbCdcBoards = ['esp32-c6-devkitc-1', 'seeed_xiao_esp32c6', 'esp32-s3-devkitc-1']
  const needsUsbCdc = usbCdcBoards.includes(resolvedBoard)

  // ESP32-C6 requires Arduino-ESP32 v3.x which is only in pioarduino fork
  const esp32c6Boards = ['esp32-c6-devkitc-1', 'seeed_xiao_esp32c6']
  const isC6 = esp32c6Boards.includes(resolvedBoard)

  // Use appropriate platform:
  // - C6 boards need pioarduino fork with Arduino 3.x support
  // - Other boards use official espressif32@6.5.0 for stability
  const platformUrl = isC6
    ? 'https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip'
    : 'espressif32@6.5.0'

  return `; PlatformIO Project Configuration
; Generated by PHAESTUS compile service

[env:${resolvedBoard.replace(/-/g, '_')}]
platform = ${platformUrl}
board = ${resolvedBoard}
framework = ${framework}

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
${needsUsbCdc ? `    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1` : ''}

; Monitor settings
monitor_speed = 115200

; Partition table
board_build.partitions = default.csv
`
}

/**
 * Execute PlatformIO compile
 */
async function runPlatformIO(projectDir: string): Promise<{ success: boolean; output: string }> {
  return new Promise((resolve) => {
    const args = ['run', '--project-dir', projectDir]
    const proc = spawn('pio', args, {
      cwd: projectDir,
      env: {
        ...process.env,
        PLATFORMIO_CORE_DIR: path.join(os.homedir(), '.platformio'),
      },
    })

    let output = ''
    let errorOutput = ''

    proc.stdout.on('data', (data) => {
      const str = data.toString()
      output += str
      console.log('[PIO]', str.trim())
    })

    proc.stderr.on('data', (data) => {
      const str = data.toString()
      errorOutput += str
      console.error('[PIO ERR]', str.trim())
    })

    // Timeout after 5 minutes
    let killed = false
    const timeout = setTimeout(() => {
      killed = true
      proc.kill('SIGTERM')
      // Escalate to SIGKILL if still running after 10s grace period
      setTimeout(() => {
        if (!proc.killed) {
          console.warn('[PIO] Process did not exit after SIGTERM, sending SIGKILL')
          proc.kill('SIGKILL')
        }
      }, 10_000)
    }, 5 * 60 * 1000)

    proc.on('close', (code) => {
      clearTimeout(timeout)
      resolve({
        success: !killed && code === 0,
        output: output + (killed ? '\n[TIMEOUT] Compilation timed out after 5 minutes' : '') + (errorOutput ? '\n--- STDERR ---\n' + errorOutput : ''),
      })
    })

    proc.on('error', (err) => {
      clearTimeout(timeout)
      resolve({
        success: false,
        output: output + `\n[ERROR] Failed to start PlatformIO: ${err.message}`,
      })
    })
  })
}

/**
 * Find the compiled firmware binary
 */
async function findFirmwareBinary(projectDir: string, board: string): Promise<string | null> {
  // PlatformIO outputs to .pio/build/<env>/firmware.bin
  const buildDir = path.join(projectDir, '.pio', 'build')

  try {
    const envDirs = await fs.readdir(buildDir)
    for (const envDir of envDirs) {
      const firmwarePath = path.join(buildDir, envDir, 'firmware.bin')
      try {
        await fs.access(firmwarePath)
        return firmwarePath
      } catch {
        // Try bootloader merged firmware
        const mergedPath = path.join(buildDir, envDir, 'firmware_merged.bin')
        try {
          await fs.access(mergedPath)
          return mergedPath
        } catch {
          continue
        }
      }
    }
  } catch {
    // Build directory doesn't exist
  }

  return null
}

/**
 * Main compile function
 */
export async function compileFirmware(input: CompileInput): Promise<CompileResult> {
  const baseDir = path.join(os.tmpdir(), 'pio-build')
  await fs.mkdir(baseDir, { recursive: true })
  const projectDir = await fs.mkdtemp(path.join(baseDir, 'project-'))

  try {
    // Create project directory structure
    await fs.mkdir(projectDir, { recursive: true })
    await fs.mkdir(path.join(projectDir, 'src'), { recursive: true })
    await fs.mkdir(path.join(projectDir, 'include'), { recursive: true })
    await fs.mkdir(path.join(projectDir, 'lib'), { recursive: true })

    // Check if platformio.ini is provided
    const platformioIniFile = input.files.find((f) => f.path === 'platformio.ini')

    if (platformioIniFile) {
      // Use provided platformio.ini
      await fs.writeFile(
        path.join(projectDir, 'platformio.ini'),
        platformioIniFile.content
      )
    } else {
      // Generate platformio.ini
      const iniContent = generatePlatformioIni(input.board, input.framework)
      await fs.writeFile(path.join(projectDir, 'platformio.ini'), iniContent)
    }

    // Write all other files
    for (const file of input.files) {
      if (file.path === 'platformio.ini') continue // Already handled

      // Normalize path (handle both src/main.cpp and main.cpp)
      let filePath = file.path
      if (filePath === 'main.cpp') {
        filePath = 'src/main.cpp'
      }

      const fullPath = resolveSafeProjectPath(projectDir, filePath)
      const dir = path.dirname(fullPath)

      // Create directory if needed
      await fs.mkdir(dir, { recursive: true })
      await fs.writeFile(fullPath, file.content)
    }

    console.log(`Project created at ${projectDir}`)
    console.log('Files:', await fs.readdir(projectDir))
    console.log('src:', await fs.readdir(path.join(projectDir, 'src')).catch(() => []))

    // Run PlatformIO
    const result = await runPlatformIO(projectDir)

    if (!result.success) {
      return {
        success: false,
        buildOutput: result.output,
        error: 'Compilation failed. See build output for details.',
      }
    }

    // Find and read firmware binary
    const firmwarePath = await findFirmwareBinary(projectDir, input.board)

    if (!firmwarePath) {
      return {
        success: false,
        buildOutput: result.output,
        error: 'Compilation succeeded but firmware binary not found',
      }
    }

    const firmware = await fs.readFile(firmwarePath)
    console.log(`Firmware compiled successfully: ${firmware.length} bytes`)

    return {
      success: true,
      firmware,
      buildOutput: result.output,
    }
  } catch (error) {
    return {
      success: false,
      buildOutput: '',
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  } finally {
    // Clean up project directory
    try {
      await fs.rm(projectDir, { recursive: true, force: true })
    } catch {
      console.warn(`Failed to clean up ${projectDir}`)
    }
  }
}
