/**
 * Enclosure Stage Subgraph
 *
 * Handles the enclosure design stage of the hardware design pipeline:
 * 1. Dimension Analysis - Calculate enclosure dimensions from PCB
 * 2. OpenSCAD Generation - Generate parametric enclosure code
 * 3. Review Loop - Iterate on design based on feedback
 */

import { StateGraph, START, END, type GraphNode } from '@langchain/langgraph'
import { AIMessage } from '@langchain/core/messages'
import {
  EnclosureStateSchema,
  type EnclosureState,
  createEnclosureDebugStep,
  calculateEnclosureDimensions,
  isOpenSCADValid,
  isReviewComplete,
  addIteration,
} from '../states/enclosure'

// =============================================================================
// Node Implementations
// =============================================================================

/**
 * Dimension Analysis Node
 *
 * Analyzes PCB dimensions and component heights to determine
 * the required enclosure dimensions.
 */
const dimensionAnalysisNode: GraphNode<typeof EnclosureStateSchema> = async (state) => {
  const startTime = Date.now()

  // TODO: Get actual PCB dimensions from PCB stage
  // For now, use placeholder values
  const pcbWidth = 50.8
  const pcbHeight = 38.1

  const dimensions = calculateEnclosureDimensions(pcbWidth, pcbHeight, {
    topClearance: 12, // For display and components
    bottomClearance: 3, // For PCB standoffs
    wallThickness: 2,
  })

  const responseMessage = new AIMessage({
    id: crypto.randomUUID(),
    content: `Enclosure dimensions calculated:\n• External: ${dimensions.externalWidth} x ${dimensions.externalHeight} x ${dimensions.externalDepth} mm\n• Wall thickness: ${dimensions.wallThickness} mm`,
  })

  const debugStep = createEnclosureDebugStep(
    'dimension_analysis',
    { pcbWidth, pcbHeight },
    { dimensions },
    Date.now() - startTime
  )

  return {
    messages: [responseMessage],
    dimensions,
    enclosureRoute: 'generate_openscad',
    debug: {
      ...state.debug,
      steps: [debugStep],
    },
  }
}

/**
 * OpenSCAD Generation Node
 *
 * Generates OpenSCAD code for the enclosure based on
 * dimensions, style, and features.
 */
const openscadGenerationNode: GraphNode<typeof EnclosureStateSchema> = async (state) => {
  const startTime = Date.now()

  if (!state.dimensions) {
    return {
      enclosureRoute: 'analyze_dimensions',
    }
  }

  // TODO: Call LLM to generate OpenSCAD code
  // For now, generate a basic parametric box
  const d = state.dimensions
  const openScadCode = `// Enclosure for Smart Environmental Monitor
// Generated by PHAESTUS
// Style: ${state.style}

// Parameters
pcb_width = ${d.pcbWidth};
pcb_height = ${d.pcbHeight};
pcb_thickness = ${d.pcbThickness};
wall = ${d.wallThickness};
top_clearance = ${d.topClearance};
bottom_clearance = ${d.bottomClearance};

// Calculated dimensions
inner_width = pcb_width + 1; // 0.5mm clearance each side
inner_height = pcb_height + 1;
inner_depth = pcb_thickness + top_clearance + bottom_clearance;

// Main enclosure
module enclosure() {
  difference() {
    // Outer shell
    cube([inner_width + wall*2, inner_height + wall*2, inner_depth + wall*2]);

    // Inner cavity
    translate([wall, wall, wall])
      cube([inner_width, inner_height, inner_depth + 1]);
  }
}

// Lid
module lid() {
  cube([inner_width + wall*2, inner_height + wall*2, wall]);
}

// Render
enclosure();
translate([0, 0, inner_depth + wall*2 + 5])
  lid();
`

  const responseMessage = new AIMessage({
    id: crypto.randomUUID(),
    content: `OpenSCAD enclosure generated with ${state.style} style. The design includes a main body and separate lid.`,
  })

  const debugStep = createEnclosureDebugStep(
    'openscad_generation',
    { dimensions: state.dimensions, style: state.style },
    { codeLength: openScadCode.length },
    Date.now() - startTime
  )

  return {
    messages: [responseMessage],
    openScadCode,
    enclosureRoute: 'review',
    debug: {
      ...state.debug,
      steps: [debugStep],
    },
  }
}

/**
 * Review Loop Node
 *
 * Handles user feedback and regenerates the enclosure if needed.
 */
const reviewLoopNode: GraphNode<typeof EnclosureStateSchema> = async (state) => {
  const startTime = Date.now()

  // Check if we have user feedback to process
  if (state.userFeedback) {
    // Store the feedback and trigger regeneration
    const newIterations = addIteration(
      state.iterations,
      state.userFeedback,
      state.openScadCode,
      state.stlUrl ?? undefined
    )

    const debugStep = createEnclosureDebugStep(
      'review_loop',
      { feedback: state.userFeedback },
      { iterationCount: newIterations.length },
      Date.now() - startTime
    )

    return {
      iterations: newIterations,
      reviewFeedback: [...state.reviewFeedback, state.userFeedback],
      userFeedback: null,
      reviewRound: state.reviewRound + 1,
      enclosureRoute: 'regenerate',
      debug: {
        ...state.debug,
        steps: [debugStep],
      },
    }
  }

  // Check if review is complete
  if (isReviewComplete(state)) {
    const responseMessage = new AIMessage({
      id: crypto.randomUUID(),
      content: `Enclosure design finalized after ${state.reviewRound} review rounds.`,
    })

    const debugStep = createEnclosureDebugStep(
      'review_loop',
      { reviewRound: state.reviewRound },
      { complete: true },
      Date.now() - startTime
    )

    return {
      messages: [responseMessage],
      stlGenerated: true,
      enclosureRoute: 'complete',
      debug: {
        ...state.debug,
        steps: [debugStep],
      },
    }
  }

  // Waiting for user review
  const responseMessage = new AIMessage({
    id: crypto.randomUUID(),
    content: `Please review the enclosure design. Provide feedback for changes or approve to continue.`,
  })

  const debugStep = createEnclosureDebugStep(
    'review_loop',
    { waitingForFeedback: true },
    { reviewRound: state.reviewRound },
    Date.now() - startTime
  )

  return {
    messages: [responseMessage],
    debug: {
      ...state.debug,
      steps: [debugStep],
    },
  }
}

// =============================================================================
// Routing Functions
// =============================================================================

/**
 * Route after dimension analysis
 */
function routeAfterDimensionAnalysis(state: EnclosureState): string {
  if (!state.dimensions) {
    return END // Error state
  }
  return 'openscad_generation'
}

/**
 * Route after OpenSCAD generation
 */
function routeAfterOpenSCAD(state: EnclosureState): string {
  if (!isOpenSCADValid(state.openScadCode)) {
    return 'openscad_generation' // Retry
  }
  return 'review_loop'
}

/**
 * Route after review loop
 */
function routeAfterReview(state: EnclosureState): string {
  if (state.enclosureRoute === 'complete') {
    return END
  }
  if (state.enclosureRoute === 'regenerate') {
    return 'openscad_generation'
  }
  // Waiting for user input
  return END
}

// =============================================================================
// Graph Builder
// =============================================================================

/**
 * Create the Enclosure stage subgraph
 */
export function createEnclosureGraph() {
  const graph = new StateGraph(EnclosureStateSchema)
    // Add nodes
    .addNode('dimension_analysis', dimensionAnalysisNode)
    .addNode('openscad_generation', openscadGenerationNode)
    .addNode('review_loop', reviewLoopNode)

    // Entry point
    .addEdge(START, 'dimension_analysis')

    // Conditional routing
    .addConditionalEdges('dimension_analysis', routeAfterDimensionAnalysis, {
      openscad_generation: 'openscad_generation',
      [END]: END,
    })
    .addConditionalEdges('openscad_generation', routeAfterOpenSCAD, {
      openscad_generation: 'openscad_generation',
      review_loop: 'review_loop',
    })
    .addConditionalEdges('review_loop', routeAfterReview, {
      openscad_generation: 'openscad_generation',
      [END]: END,
    })

  return graph
}

/**
 * Compile the Enclosure subgraph
 */
export function compileEnclosureGraph() {
  return createEnclosureGraph().compile()
}

// Export node names for visualization
export const ENCLOSURE_NODES = ['dimension_analysis', 'openscad_generation', 'review_loop'] as const

export type EnclosureNodeName = (typeof ENCLOSURE_NODES)[number]
