/**
 * Firmware Stage Subgraph
 *
 * Handles the firmware development stage of the hardware design pipeline:
 * 1. Component Analysis - Analyze PCB components for pin mapping
 * 2. Code Generation - Generate ESP32-C6 firmware
 * 3. Review Loop - Iterate on code based on review feedback
 */

import { StateGraph, START, END, type GraphNode } from '@langchain/langgraph'
import { AIMessage } from '@langchain/core/messages'
import {
  FirmwareStateSchema,
  type FirmwareState,
  createFirmwareDebugStep,
  upsertFile,
  hasCriticalIssues,
  isReviewComplete,
  generatePlatformioIni,
} from '../states/firmware'

// =============================================================================
// Node Implementations
// =============================================================================

/**
 * Component Analysis Node
 *
 * Analyzes the PCB components to determine pin mappings,
 * I2C addresses, and SPI configurations.
 */
const componentAnalysisNode: GraphNode<typeof FirmwareStateSchema> = async (state) => {
  const startTime = Date.now()

  // TODO: Get actual component info from PCB stage
  // For now, use placeholder data
  const pinMappings = [
    { component: 'BME280', pin: 'SDA', gpio: 'GPIO6', function: 'I2C Data' },
    { component: 'BME280', pin: 'SCL', gpio: 'GPIO7', function: 'I2C Clock' },
    { component: 'OLED', pin: 'SDA', gpio: 'GPIO6', function: 'I2C Data (shared)' },
    { component: 'OLED', pin: 'SCL', gpio: 'GPIO7', function: 'I2C Clock (shared)' },
    { component: 'WS2812B', pin: 'DIN', gpio: 'GPIO8', function: 'LED Data' },
  ]

  const i2cDevices = [
    {
      name: 'BME280',
      address: '0x76',
      blockSlug: 'sensor-bme280',
      sdaPin: 'GPIO6',
      sclPin: 'GPIO7',
    },
    {
      name: 'SSD1306',
      address: '0x3C',
      blockSlug: 'display-oled',
      sdaPin: 'GPIO6',
      sclPin: 'GPIO7',
    },
  ]

  const responseMessage = new AIMessage({
    id: crypto.randomUUID(),
    content: `Component analysis complete:\n• ${pinMappings.length} pin mappings identified\n• ${i2cDevices.length} I2C devices found`,
  })

  const debugStep = createFirmwareDebugStep(
    'component_analysis',
    { userRequest: state.userRequest },
    { pinMappings: pinMappings.length, i2cDevices: i2cDevices.length },
    Date.now() - startTime
  )

  return {
    messages: [responseMessage],
    pinMappings,
    i2cDevices,
    firmwareRoute: 'generate_code',
    debug: {
      ...state.debug,
      steps: [debugStep],
    },
  }
}

/**
 * Code Generation Node
 *
 * Generates the firmware code based on component analysis
 * and user requirements.
 */
const codeGenerationNode: GraphNode<typeof FirmwareStateSchema> = async (state) => {
  const startTime = Date.now()

  // TODO: Call LLM to generate firmware code
  // For now, generate placeholder code
  const mainCpp = `/**
 * Smart Environmental Monitor Firmware
 * Generated by PHAESTUS
 *
 * Target: ESP32-C6
 * Framework: PlatformIO
 */

#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_BME280.h>
#include <Adafruit_SSD1306.h>
#include <Adafruit_NeoPixel.h>

// Pin definitions
#define I2C_SDA 6
#define I2C_SCL 7
#define LED_PIN 8
#define LED_COUNT 1

// I2C addresses
#define BME280_ADDR 0x76
#define OLED_ADDR 0x3C

// Display dimensions
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

// Sensor and display objects
Adafruit_BME280 bme;
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);
Adafruit_NeoPixel led(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);

// Timing
unsigned long lastUpdate = 0;
const unsigned long updateInterval = 1000; // 1 second

void setup() {
  Serial.begin(115200);

  // Initialize I2C
  Wire.begin(I2C_SDA, I2C_SCL);

  // Initialize BME280
  if (!bme.begin(BME280_ADDR)) {
    Serial.println("BME280 not found!");
  }

  // Initialize OLED
  if (!display.begin(SSD1306_SWITCHCAPVCC, OLED_ADDR)) {
    Serial.println("SSD1306 not found!");
  }
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);

  // Initialize LED
  led.begin();
  led.setBrightness(50);
  led.show();

  Serial.println("Initialization complete!");
}

void loop() {
  if (millis() - lastUpdate >= updateInterval) {
    lastUpdate = millis();

    // Read sensors
    float temp = bme.readTemperature();
    float humidity = bme.readHumidity();
    float pressure = bme.readPressure() / 100.0F;

    // Update display
    display.clearDisplay();
    display.setCursor(0, 0);
    display.printf("Temp: %.1f C\\n", temp);
    display.printf("Humidity: %.1f%%\\n", humidity);
    display.printf("Pressure: %.1f hPa\\n", pressure);
    display.display();

    // Update LED color based on temperature
    uint8_t r = map(temp, 15, 35, 0, 255);
    uint8_t b = map(temp, 15, 35, 255, 0);
    led.setPixelColor(0, led.Color(r, 0, b));
    led.show();

    // Serial output
    Serial.printf("T: %.1f C, H: %.1f%%, P: %.1f hPa\\n", temp, humidity, pressure);
  }
}
`

  const platformioIni = generatePlatformioIni(state.targetMcu)

  // Create/update files
  let files = upsertFile(state.files, {
    path: 'src/main.cpp',
    content: mainCpp,
    language: 'cpp',
  })
  files = upsertFile(files, {
    path: 'platformio.ini',
    content: platformioIni,
    language: 'json',
  })

  const responseMessage = new AIMessage({
    id: crypto.randomUUID(),
    content: `Firmware generated:\n• main.cpp - Main application code\n• platformio.ini - Build configuration\n\nThe code reads BME280 sensor data and displays it on the OLED.`,
  })

  const debugStep = createFirmwareDebugStep(
    'code_generation',
    { pinMappings: state.pinMappings.length, i2cDevices: state.i2cDevices.length },
    { files: files.length },
    Date.now() - startTime
  )

  return {
    messages: [responseMessage],
    files,
    firmwareRoute: 'review',
    debug: {
      ...state.debug,
      steps: [debugStep],
    },
  }
}

/**
 * Review Loop Node
 *
 * Reviews the generated code and handles user feedback.
 */
const reviewLoopNode: GraphNode<typeof FirmwareStateSchema> = async (state) => {
  const startTime = Date.now()

  // Check if we have user feedback
  if (state.userFeedback) {
    const debugStep = createFirmwareDebugStep(
      'review_loop',
      { feedback: state.userFeedback },
      { regenerating: true },
      Date.now() - startTime
    )

    return {
      reviewFeedback: [...state.reviewFeedback, state.userFeedback],
      userFeedback: null,
      reviewRound: state.reviewRound + 1,
      firmwareRoute: 'regenerate',
      debug: {
        ...state.debug,
        steps: [debugStep],
      },
    }
  }

  // TODO: Run automated code review
  // For now, no issues found
  const reviewIssues = state.reviewIssues

  // Check if review is complete
  if (isReviewComplete(state) || !hasCriticalIssues(reviewIssues)) {
    const responseMessage = new AIMessage({
      id: crypto.randomUUID(),
      content: `Firmware review complete!\n• ${state.files.length} files generated\n• No critical issues found\n\nThe firmware is ready for compilation.`,
    })

    const debugStep = createFirmwareDebugStep(
      'review_loop',
      { reviewRound: state.reviewRound, issueCount: reviewIssues.length },
      { validated: true },
      Date.now() - startTime
    )

    return {
      messages: [responseMessage],
      validated: true,
      firmwareRoute: 'complete',
      debug: {
        ...state.debug,
        steps: [debugStep],
      },
    }
  }

  // Has issues, need to fix
  const debugStep = createFirmwareDebugStep(
    'review_loop',
    { issueCount: reviewIssues.length },
    { needsFix: true },
    Date.now() - startTime
  )

  return {
    firmwareRoute: 'regenerate',
    debug: {
      ...state.debug,
      steps: [debugStep],
    },
  }
}

// =============================================================================
// Routing Functions
// =============================================================================

/**
 * Route after component analysis
 */
function routeAfterComponentAnalysis(state: FirmwareState): string {
  if (state.pinMappings.length === 0) {
    return END // No components to program
  }
  return 'code_generation'
}

/**
 * Route after code generation
 */
function routeAfterCodeGeneration(state: FirmwareState): string {
  if (state.files.length === 0) {
    return 'code_generation' // Retry
  }
  return 'review_loop'
}

/**
 * Route after review loop
 */
function routeAfterReview(state: FirmwareState): string {
  if (state.firmwareRoute === 'complete') {
    return END
  }
  if (state.firmwareRoute === 'regenerate') {
    return 'code_generation'
  }
  // Waiting for user input
  return END
}

// =============================================================================
// Graph Builder
// =============================================================================

/**
 * Create the Firmware stage subgraph
 */
export function createFirmwareGraph() {
  const graph = new StateGraph(FirmwareStateSchema)
    // Add nodes
    .addNode('component_analysis', componentAnalysisNode)
    .addNode('code_generation', codeGenerationNode)
    .addNode('review_loop', reviewLoopNode)

    // Entry point
    .addEdge(START, 'component_analysis')

    // Conditional routing
    .addConditionalEdges('component_analysis', routeAfterComponentAnalysis, {
      code_generation: 'code_generation',
      [END]: END,
    })
    .addConditionalEdges('code_generation', routeAfterCodeGeneration, {
      code_generation: 'code_generation',
      review_loop: 'review_loop',
    })
    .addConditionalEdges('review_loop', routeAfterReview, {
      code_generation: 'code_generation',
      [END]: END,
    })

  return graph
}

/**
 * Compile the Firmware subgraph
 */
export function compileFirmwareGraph() {
  return createFirmwareGraph().compile()
}

// Export node names for visualization
export const FIRMWARE_NODES = ['component_analysis', 'code_generation', 'review_loop'] as const

export type FirmwareNodeName = (typeof FIRMWARE_NODES)[number]
