/**
 * Utility functions for firmware file tree operations
 */

import type { FileNode } from './types'
import type { FirmwareProject } from '@/prompts/firmware'

/**
 * Flatten file tree into array of {path, content} pairs
 */
export function flattenFiles(nodes: FileNode[]): { path: string; content: string }[] {
  const result: { path: string; content: string }[] = []
  for (const node of nodes) {
    if (node.type === 'file' && node.content) {
      result.push({ path: node.path, content: node.content })
    }
    if (node.children) {
      result.push(...flattenFiles(node.children))
    }
  }
  return result
}

/**
 * Build file tree structure from flat file list
 */
export function buildFileTree(files: FirmwareProject['files']): FileNode[] {
  const root: FileNode[] = []

  for (const file of files) {
    const parts = file.path.split('/')
    let current = root

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i]
      const isLast = i === parts.length - 1

      if (isLast) {
        current.push({
          name: part,
          path: file.path,
          type: 'file',
          content: file.content,
          language: file.language === 'h' ? 'cpp' : file.language === 'ini' ? 'ini' : 'cpp',
        })
      } else {
        let folder = current.find((n) => n.name === part && n.type === 'folder')
        if (!folder) {
          folder = {
            name: part,
            path: parts.slice(0, i + 1).join('/'),
            type: 'folder',
            children: [],
          }
          current.push(folder)
        }
        current = folder.children!
      }
    }
  }

  return root
}

/**
 * Find a node in the tree by path
 */
export function findNode(nodes: FileNode[], path: string): FileNode | null {
  for (const node of nodes) {
    if (node.path === path) return node
    if (node.children) {
      const found = findNode(node.children, path)
      if (found) return found
    }
  }
  return null
}

/**
 * Update content of a file in the tree (immutable)
 */
export function updateFileContent(
  nodes: FileNode[],
  path: string,
  content: string
): FileNode[] {
  return nodes.map((node) => {
    if (node.path === path) {
      return { ...node, content }
    }
    if (node.children) {
      return { ...node, children: updateFileContent(node.children, path, content) }
    }
    return node
  })
}

/**
 * Convert file tree to FirmwareProject files format
 */
export function getFilesForSave(
  currentFileTree: FileNode[],
  currentPath?: string,
  currentContent?: string
): FirmwareProject['files'] {
  const files = flattenFiles(currentFileTree)
  return files.map((f) => ({
    path: f.path,
    // Use current editor content for the active file
    content: currentPath && f.path === currentPath ? currentContent || '' : f.content || '',
    language: (f.path.endsWith('.h') ? 'h' : f.path.endsWith('.ini') ? 'ini' : 'cpp') as
      | 'cpp'
      | 'h'
      | 'ini'
      | 'json',
  }))
}

/**
 * Generate README content for firmware ZIP
 */
export function generateReadme(projectName: string): string {
  return `# ${projectName || 'PHAESTUS'} Firmware

Generated by PHAESTUS Hardware Design Platform

## Building with PlatformIO

1. Install PlatformIO: https://platformio.org/install
2. Open this folder in VS Code with PlatformIO extension
3. Click "Build" in the PlatformIO toolbar
4. Click "Upload" to flash to your ESP32-C6

## Manual Build

\`\`\`bash
# Install PlatformIO CLI
pip install platformio

# Build
cd ${projectName?.toLowerCase().replace(/\s+/g, '-') || 'firmware'}
pio run

# Upload to device
pio run -t upload
\`\`\`

## Binary Output

After building, find the binary at:
\`.pio/build/esp32c6/firmware.bin\`

Upload this .bin file back to PHAESTUS for distribution.
`
}
